blank_issues_enabled: true
contact_links:
  - name: Help
    url: https://odpf-community.slack.com/archives/C01LMME51QC
    about: "If you have a question or need help, ask a question on the discussion forums."
  - name: Show and tell
    url: https://odpf-community.slack.com/archives/C01LCE0CYQM
    about: "Have something nice to show and tell? We'd love to hear it!"
